version: "3.7"
services:
    node-youtube-dl:
        image: itlboy/youtube-dl-from-csv
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - ./download:/download
#            - ./:/app
            - ./list.csv:/list.csv
        environment:
            FORMAT: mp4
        restart: always    